title: Configuration development
class: \Drutiny\Check\D8\ModuleDisabled
tags:
  - Drupal 8
  - Best Practice
  - Performance
  - Security
description: |
  This module helps with developing configuration. Do not deploy in production
  environments. Exercise caution and always use version control.
remediation: "Disable the module: `drush pm-uninstall config_devel -y`"
success: The Configuration development module is not currently enabled.
failure: The Configuration development module is currently enabled.
parameters:
  module:
    type: string
    description: The name of the module to ensure is disabled.
    default: config_devel
